# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('code', models.IntegerField()),
                ('affects_gwa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('units', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prerequisites', models.ManyToManyField(related_name='prerequisite', to='core.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('class_attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sid', models.IntegerField(unique=True)),
                ('degree_program', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('first_name', 'last_name', 'sid')]),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('name', 'number')]),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AddField(
            model_name='class',
            name='faculty',
            field=models.ManyToManyField(to='core.Faculty'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set([('grade', 'student', 'class_attr')]),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('name', 'units')]),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([('section', 'code', 'semester', 'course')]),
        ),
    ]
