# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170618_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='substitutes',
            field=models.ManyToManyField(related_name='substitutes_to', to='core.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(related_name='prerequisites_to', to='core.Course'),
        ),
    ]
