# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170618_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enlistment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=50)),
                ('accountability', models.CharField(max_length=50)),
                ('classes', models.ManyToManyField(to='core.Class')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enlistment',
            unique_together=set([('student', 'semester')]),
        ),
    ]
